openapi: 3.0.1
info: 
  title: User behavioral data analyzer
  description: 'Distributed analytics system'
  version: 1.0.0
servers:
  - url: /v1
paths: 
  /users/{user-uuid}/clicks:
    get:
      parameters:
        - name: user-uuid
          in: path
          description: User uuid for which the counts should be calculated
          required: true
          schema:
            type: string
            example: 3588b44b-ec83-430a-85f1-c4eb6d50ec16
        - name: timePeriod
          in: query
          description: Time period in minutes for which the counts should be calculated
          required: true
          schema:
            type: integer
            format: int32
            example: 30
      responses: 
        200:
          description: Average clicks count user performed during the given time period
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClicksCountResponse'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{user-uuid}/timespent:
    get:
      parameters:
        - name: user-uuid
          in: path
          description: User uuid for which the time spent should be calculated
          required: true
          schema:
            type: string
            example: 3588b44b-ec83-430a-85f1-c4eb6d50ec16
        - name: screen
          in: query
          description: The screen for which the time spent should be calculated
          required: true
          schema:
            type: string
            enum: [home, account, notifications, settings]
            example: home
      responses: 
        200:
          description: Average time user spent on the corresponding screen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeSpentResponse'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas: 
    ClicksCountResponse:
      type: object
      properties: 
        count:
          type: integer
          format: int32
      required:
        - count
    TimeSpentResponse:
      type: object
      properties: 
        time-spent:
          type: string
      required:
        - time-spent
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
